const ROLES = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  LAB_TECH: 'LAB_TECH',
  PATIENT: 'PATIENT'
};

const APPOINTMENT_STATUS = {
  SCHEDULED: 'SCHEDULED',
  CHECKED_IN: 'CHECKED_IN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW'
};

const LAB_ORDER_STATUS = {
  ORDERED: 'ORDERED',
  SAMPLE_COLLECTED: 'SAMPLE_COLLECTED',
  PROCESSING: 'PROCESSING',
  VERIFIED: 'VERIFIED',
  RELEASED: 'RELEASED'
};

const LAB_RESULT_STATUS = {
  DRAFT: 'DRAFT',
  VERIFIED: 'VERIFIED',
  RELEASED: 'RELEASED'
};

const INVOICE_STATUS = {
  UNPAID: 'UNPAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
};

const SERVICE_CATEGORY = {
  CONSULTATION: 'Consultation',
  LABORATORY: 'Laboratory',
  PROCEDURE: 'Procedure',
  IMAGING: 'Imaging'
};

module.exports = {
  ROLES,
  APPOINTMENT_STATUS,
  LAB_ORDER_STATUS,
  LAB_RESULT_STATUS,
  INVOICE_STATUS,
  SERVICE_CATEGORY
};
